name: Create New Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the new version number (e.g., 1.0.1)"
        required: true
        default: "1.0.0"

jobs:
  create-release:
    runs-on: macos-latest
    steps:
      - name: Checkout the primary repository (Actions Repo)
        uses: actions/checkout@v3
        with:
          repository: vedantgurav/fieldday-ios-sdk-actions-test
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Homebrew (if needed)
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi

      - name: Install swift-create-xcframework
        run: |
          git clone https://github.com/unsignedapps/swift-create-xcframework.git
          cd swift-create-xcframework
          make install


      - name: Clone the Source Code Repo
        run: git clone https://github.com/vedantgurav/fieldday-ios-sdk-source-actions-test.git

      - name: Build XCFramework and Create Zip
        run: |
          cd fieldday-ios-sdk-source-actions-test
          swift create-xcframework --zip-version ${{ github.event.inputs.version }}

      - name: Rename Zip File
        run: |
          cd fieldday-ios-sdk-source-actions-test
          mv "fieldday-ios-source-${{ github.event.inputs.version }}.zip" "FieldDay-${{ github.event.inputs.version }}.zip"

      - name: Calculate SHA256 Checksum
        id: checksum
        run: |
          cd fieldday-ios-sdk-source-actions-test
          shasum -a 256 "FieldDay-${{ github.event.inputs.version }}.zip" | awk '{ print $1 }'

      - name: Update Package.swift in the SDK Repo
        run: |
          git clone https://github.com/vedantgurav/fieldday-ios-sdk-actions-test.git
          cd fieldday-ios-sdk-actions-test
          sed -i '' "s|https://github.com/fieldday-ai/fieldday-ios-sdk/releases/download/.*/FieldDay-.*.zip|https://github.com/fieldday-ai/fieldday-ios-sdk/releases/download/${{ github.event.inputs.version }}/FieldDay-${{ github.event.inputs.version }}.zip|g" Package.swift
          sed -i '' "s|checksum: \".*\"|checksum: \"${{ steps.checksum.outputs.checksum }}\"|g" Package.swift
          git add Package.swift
          git commit -m "Update Package.swift for version ${{ github.event.inputs.version }}"
          git push origin main

      - name: Create GitHub Release in SDK Repo
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: vedantgurav/fieldday-ios-sdk-actions-test
          tag: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: fieldday-ios-sdk-source-actions-test/FieldDay-${{ github.event.inputs.version }}.zip
          body: "Release for version ${{ github.event.inputs.version }}"

      - name: Clean Up
        run: rm -rf fieldday-ios-sdk-source-actions-test fieldday-ios-sdk-actions-test
