name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New Version Number'
        required: true

jobs:

  create-release:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: fieldday-ai/fieldday-ios-sdk-source
        
    - name: Create XCFramework
      uses: unsignedapps/swift-create-xcframework@v2
      with:
        version: ${{ github.event.inputs.version }}
        
    - name: Update Package.swift
      uses: actions/checkout@v2
      with:
        repository: fieldday-ai/fieldday-ios-sdk
        
    - name: Update Package.swift
      run: |
        git clone https://github.com/fieldday-ai/fieldday-ios-sdk.git
        cd fieldday-ios-sdk
        
        current_version=$(grep -oP "version: \"\K[^\"]*" Package.swift)
        
        new_version=${{ github.event.inputs.version }}
        new_checksum=$(cat FieldDay-$new_version.zip.sha256)
        
        sed -i '' "s/$current_version/$new_version/g" Package.swift
        sed -i '' "s/checksum: \"[^\"]*\"/checksum: \"$new_checksum\"/g" Package.swift
        
        git add Package.swift
        git commit -m "Update to version $new_version"
        git push
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: ${{ github.event.inputs.version }}
        draft: false
        prerelease: false
        asset_path: FieldDay-${{ github.event.inputs.version }}.zip
        asset_name: FieldDay-${{ github.event.inputs.version }}.zip
        asset_content_type: application/zip
